export type Language = 'en' | 'zh' | 'ja' | 'ko' | 'de';

export const platformAgreements = [
  {
    name: 'GitHub Copilot',
    clause: { en: 'Public code used to train Copilot. Business plans may use your code for model improvement.', zh: '公开代码被用于训练 Copilot。商业版可能使用你的代码进行模型改进。', ja: '公開コードがCopilotの訓練に使用。ビジネスプランではコードがモデル改善に使われる可能性。', ko: '공개 코드가 Copilot 훈련에 사용됨. 비즈니스 플랜에서 코드가 모델 개선에 사용될 수 있음.', de: 'Öffentlicher Code wird für Copilot-Training verwendet. Business-Pläne können Ihren Code zur Modellverbesserung nutzen.' },
    risk: 'high' as const,
    trains: { en: 'Code generation AI → replaces junior developers', zh: '代码生成 AI → 替代初级开发者', ja: 'コード生成AI → ジュニア開発者を代替', ko: '코드 생성 AI → 주니어 개발자 대체', de: 'Code-Generierungs-KI → ersetzt Junior-Entwickler' },
  },
  {
    name: 'ChatGPT / OpenAI',
    clause: { en: 'Conversations used for model training unless opted out in settings.', zh: '对话内容默认用于模型训练，除非在设置中关闭。', ja: '設定でオプトアウトしない限り、会話がモデル訓練に使用。', ko: '설정에서 옵트아웃하지 않으면 대화가 모델 훈련에 사용됨.', de: 'Gespräche werden für Modelltraining genutzt, sofern nicht in den Einstellungen deaktiviert.' },
    risk: 'high' as const,
    trains: { en: 'General AI capabilities → replaces knowledge workers', zh: '通用 AI 能力 → 替代知识工作者', ja: '汎用AI能力 → 知識労働者を代替', ko: '범용 AI 능력 → 지식 노동자 대체', de: 'Allgemeine KI-Fähigkeiten → ersetzt Wissensarbeiter' },
  },
  {
    name: 'Google Workspace',
    clause: { en: 'Data may be used to improve AI-powered features in Workspace products.', zh: '数据可能用于改进 Workspace 产品中的 AI 功能。', ja: 'データがWorkspace製品のAI機能改善に使用される可能性。', ko: '데이터가 Workspace 제품의 AI 기능 개선에 사용될 수 있음.', de: 'Daten können zur Verbesserung KI-gestützter Workspace-Funktionen genutzt werden.' },
    risk: 'medium' as const,
    trains: { en: 'Document/email AI → replaces admin & assistants', zh: '文档/邮件 AI → 替代行政与助理', ja: '文書/メールAI → 事務・アシスタントを代替', ko: '문서/이메일 AI → 행정 및 비서 대체', de: 'Dokument/E-Mail-KI → ersetzt Verwaltung & Assistenten' },
  },
  {
    name: 'Microsoft 365 Copilot',
    clause: { en: 'Organizational data feeds AI features. Grounding data used in real-time.', zh: '组织数据为 AI 功能提供支持，实时使用基础数据。', ja: '組織データがAI機能に使用。グラウンディングデータがリアルタイムで利用。', ko: '조직 데이터가 AI 기능에 사용됨. 그라운딩 데이터가 실시간으로 활용.', de: 'Organisationsdaten speisen KI-Funktionen. Grounding-Daten werden in Echtzeit genutzt.' },
    risk: 'medium' as const,
    trains: { en: 'Office productivity AI → replaces analysts', zh: '办公效率 AI → 替代分析师', ja: 'オフィス生産性AI → アナリストを代替', ko: '오피스 생산성 AI → 분석가 대체', de: 'Office-Produktivitäts-KI → ersetzt Analysten' },
  },
  {
    name: 'LinkedIn',
    clause: { en: 'Profile data, posts, and interactions used for AI-powered recommendations and features.', zh: '个人资料、帖子和互动用于 AI 推荐和功能。', ja: 'プロフィール、投稿、インタラクションがAI推薦機能に使用。', ko: '프로필, 게시물, 상호작용이 AI 추천 기능에 사용됨.', de: 'Profildaten, Beiträge und Interaktionen werden für KI-gestützte Empfehlungen genutzt.' },
    risk: 'high' as const,
    trains: { en: 'Recruiting AI → automates hiring decisions', zh: '招聘 AI → 自动化招聘决策', ja: '採用AI → 採用判断を自動化', ko: '채용 AI → 채용 결정 자동화', de: 'Recruiting-KI → automatisiert Einstellungsentscheidungen' },
  },
  {
    name: 'Slack',
    clause: { en: 'Messages analyzed for AI search and summary features. Enterprise controls available.', zh: '消息被分析用于 AI 搜索和摘要功能。企业版可控。', ja: 'メッセージがAI検索・要約機能のために分析。エンタープライズ版で制御可能。', ko: '메시지가 AI 검색 및 요약 기능을 위해 분석됨. 엔터프라이즈 제어 가능.', de: 'Nachrichten werden für KI-Suche und Zusammenfassungen analysiert. Enterprise-Kontrollen verfügbar.' },
    risk: 'medium' as const,
    trains: { en: 'Workplace AI → automates communication workflows', zh: '职场 AI → 自动化沟通流程', ja: '職場AI → コミュニケーションワークフローを自動化', ko: '업무 AI → 커뮤니케이션 워크플로 자동화', de: 'Arbeitsplatz-KI → automatisiert Kommunikations-Workflows' },
  },
  {
    name: 'Zoom',
    clause: { en: 'Updated 2023: Meeting data may train AI. Opt-out after backlash.', zh: '2023 更新：会议数据可能训练 AI。在反对声中增加了退出选项。', ja: '2023年更新：会議データがAI訓練に使用される可能性。反発後にオプトアウト追加。', ko: '2023년 업데이트: 회의 데이터가 AI 훈련에 사용될 수 있음. 반발 후 옵트아웃 추가.', de: 'Update 2023: Meetingdaten könnten KI trainieren. Opt-out nach Gegenreaktion.' },
    risk: 'low' as const,
    trains: { en: 'Meeting AI → replaces note-takers & schedulers', zh: '会议 AI → 替代记录员和日程安排', ja: '会議AI → 議事録係・スケジューラーを代替', ko: '회의 AI → 기록자 및 스케줄러 대체', de: 'Meeting-KI → ersetzt Protokollanten & Terminplaner' },
  },
  {
    name: 'Adobe Creative Cloud',
    clause: { en: 'Creative content analyzed. Firefly trained on Adobe Stock and licensed content.', zh: '创意内容被分析。Firefly 基于 Adobe Stock 和授权内容训练。', ja: 'クリエイティブコンテンツが分析される。FireflyはAdobe Stockとライセンスコンテンツで訓練。', ko: '크리에이티브 콘텐츠가 분석됨. Firefly는 Adobe Stock과 라이선스 콘텐츠로 훈련.', de: 'Kreativinhalte werden analysiert. Firefly wird mit Adobe Stock und lizenzierten Inhalten trainiert.' },
    risk: 'high' as const,
    trains: { en: 'Image/design AI → replaces junior designers', zh: '图像/设计 AI → 替代初级设计师', ja: '画像/デザインAI → ジュニアデザイナーを代替', ko: '이미지/디자인 AI → 주니어 디자이너 대체', de: 'Bild/Design-KI → ersetzt Junior-Designer' },
  },
];

export const dataProtectionTranslations = {
  en: {
    backToHome: '← Back to Home',
    dataThreatTitle: 'Your Data Is Training AI to Replace You',
    dataThreatSubtitle: 'Skill is the last mile from general AI to your specific job. Your experience data is the last defense line.',
    lastMileTitle: 'The Last Mile Problem',
    lastMileDesc: 'A foundation model alone can\'t do your job. But add your industry data, your workflows, your expertise — and it becomes your replacement.',
    lastMileStep1: 'Foundation Model',
    lastMileStep1Desc: 'General capability, no specialization',
    lastMileStep2: 'Your Data & Experience',
    lastMileStep2Desc: 'Industry knowledge, workflows, expertise',
    lastMileStep3: 'Your Replacement',
    lastMileStep3Desc: 'AI that does YOUR specific job',
    lastMileArrow1: 'Fine-tuning / Skills',
    lastMileArrow2: 'Specialization',
    lastMileWarning: 'The more open your experience data is, the faster AI crosses the last mile to replace you.',
    platformTitle: 'What You Already Agreed To',
    platformSubtitle: 'Most people unknowingly "agreed" to let their data train AI. Here\'s what\'s in the fine print:',
    platformName: 'Platform',
    platformClause: 'AI Training Clause',
    platformRisk: 'Risk',
    platformTrains: 'What It Trains',
    platformRiskHigh: 'Explicit Training',
    platformRiskMedium: 'Ambiguous',
    platformRiskLow: 'Opt-out Available',
    feedbackLoopTitle: 'The Feedback Loop',
    feedbackLoopDesc: 'You create data → Company collects it → AI trains on it → AI replaces you → Company profits',
    feedbackLoopExample: 'Real example: Developers wrote code on GitHub → Copilot trained on it → Companies now hire fewer junior devs',
    feedbackLoopStat: 'The people who created the training data are the first to be replaced.',
    protectionTitle: 'Protect Your Last Defense Line',
    protectionSubtitle: 'Actionable steps to guard your experience data:',
    protection1: 'Review AI training opt-out settings on every platform you use',
    protection2: 'Understand your employer\'s data collection and AI training policies',
    protection3: 'Develop non-digitizable skills: judgment, relationships, physical craft',
    protection4: 'Keep proprietary knowledge in non-indexed, private formats',
    protection5: 'Know your rights: GDPR (EU) and data protection laws grant you control',
    viewFullDetails: 'View Full Data Protection Guide',
    viewFullDetailsCta: 'See what platforms collect, the feedback loop, and how to protect yourself.',
  },
  zh: {
    backToHome: '← 返回首页',
    dataThreatTitle: '你的数据正在训练 AI 来取代你',
    dataThreatSubtitle: '技能是通用 AI 到专业任务的最后一公里。你的经验数据，是最后一道防线。',
    lastMileTitle: '最后一公里问题',
    lastMileDesc: '基础模型本身做不了你的工作。但加上你的行业数据、你的工作流、你的专业知识——它就变成了你的替代者。',
    lastMileStep1: '基础模型',
    lastMileStep1Desc: '通用能力，无专业化',
    lastMileStep2: '你的数据与经验',
    lastMileStep2Desc: '行业知识、工作流程、专业技能',
    lastMileStep3: '你的替代者',
    lastMileStep3Desc: '能做你具体工作的 AI',
    lastMileArrow1: '微调 / 技能',
    lastMileArrow2: '专业化',
    lastMileWarning: '你的经验数据越开放，AI 就越快跨过最后一公里来取代你。',
    platformTitle: '你签了什么？',
    platformSubtitle: '大多数人在不知情的情况下已经"同意"了让自己的数据训练 AI。以下是细则里写的：',
    platformName: '平台',
    platformClause: 'AI 训练条款',
    platformRisk: '风险',
    platformTrains: '训练了什么',
    platformRiskHigh: '明确训练',
    platformRiskMedium: '模糊条款',
    platformRiskLow: '可选退出',
    feedbackLoopTitle: '死亡循环',
    feedbackLoopDesc: '你创造数据 → 公司收集 → AI 训练 → AI 取代你 → 公司获利',
    feedbackLoopExample: '真实案例：开发者在 GitHub 上写代码 → Copilot 用它训练 → 公司现在减少招聘初级开发者',
    feedbackLoopStat: '创造训练数据的人，是第一批被替代的人。',
    protectionTitle: '保护你的最后防线',
    protectionSubtitle: '立即可行的经验数据保护措施：',
    protection1: '检查你使用的每个平台的 AI 训练退出设置',
    protection2: '了解你的雇主的数据收集和 AI 训练政策',
    protection3: '发展不可数字化的技能：判断力、人际关系、物理技艺',
    protection4: '将专有知识保存在未被索引的私有格式中',
    protection5: '了解你的权利：GDPR（欧盟）和《个人信息保护法》赋予你数据控制权',
    viewFullDetails: '查看完整数据保护指南',
    viewFullDetailsCta: '了解平台数据收集条款、反馈循环和保护措施。',
  },
  ja: {
    backToHome: '← ホームに戻る',
    dataThreatTitle: 'あなたのデータがAIを訓練してあなたを代替する',
    dataThreatSubtitle: 'スキルは汎用AIからあなたの仕事へのラストマイル。あなたの経験データが最後の防衛線。',
    lastMileTitle: 'ラストマイル問題',
    lastMileDesc: '基盤モデルだけではあなたの仕事はできない。しかしあなたの業界データ、ワークフロー、専門知識を加えると — それがあなたの代替者になる。',
    lastMileStep1: '基盤モデル',
    lastMileStep1Desc: '汎用能力、専門化なし',
    lastMileStep2: 'あなたのデータと経験',
    lastMileStep2Desc: '業界知識、ワークフロー、専門技能',
    lastMileStep3: 'あなたの代替者',
    lastMileStep3Desc: 'あなたの具体的な仕事をするAI',
    lastMileArrow1: 'ファインチューニング / スキル',
    lastMileArrow2: '専門化',
    lastMileWarning: 'あなたの経験データがオープンであるほど、AIはラストマイルを速く越えてあなたを代替する。',
    platformTitle: 'あなたが既に同意したこと',
    platformSubtitle: 'ほとんどの人は知らずにデータをAI訓練に使うことに「同意」している。細則の内容：',
    platformName: 'プラットフォーム',
    platformClause: 'AI訓練条項',
    platformRisk: 'リスク',
    platformTrains: '何を訓練するか',
    platformRiskHigh: '明示的訓練',
    platformRiskMedium: '曖昧',
    platformRiskLow: 'オプトアウト可能',
    feedbackLoopTitle: 'フィードバックループ',
    feedbackLoopDesc: 'あなたがデータを作成 → 企業が収集 → AIが訓練 → AIがあなたを代替 → 企業が利益',
    feedbackLoopExample: '実例：開発者がGitHubでコードを書いた → Copilotがそれで訓練 → 企業はジュニア開発者の採用を減らした',
    feedbackLoopStat: '訓練データを作った人が最初に代替される。',
    protectionTitle: '最後の防衛線を守る',
    protectionSubtitle: '経験データを守るための実行可能なステップ：',
    protection1: '使用するすべてのプラットフォームでAI訓練のオプトアウト設定を確認',
    protection2: '雇用主のデータ収集とAI訓練ポリシーを理解する',
    protection3: 'デジタル化できないスキルを磨く：判断力、人間関係、物理的技能',
    protection4: '専有知識をインデックスされない非公開形式で保管',
    protection5: '権利を知る：GDPR（EU）と個人情報保護法があなたにコントロール権を与える',
    viewFullDetails: 'データ保護ガイド全文を見る',
    viewFullDetailsCta: 'プラットフォームが何を収集し、フィードバックループと保護方法を見る。',
  },
  ko: {
    backToHome: '← 홈으로 돌아가기',
    dataThreatTitle: '당신의 데이터가 AI를 훈련시켜 당신을 대체합니다',
    dataThreatSubtitle: '스킬은 범용 AI에서 당신의 직업까지의 라스트 마일. 당신의 경험 데이터가 마지막 방어선.',
    lastMileTitle: '라스트 마일 문제',
    lastMileDesc: '기반 모델만으로는 당신의 일을 할 수 없다. 하지만 당신의 업계 데이터, 워크플로, 전문 지식을 더하면 — 그것이 당신의 대체자가 된다.',
    lastMileStep1: '기반 모델',
    lastMileStep1Desc: '범용 능력, 전문화 없음',
    lastMileStep2: '당신의 데이터와 경험',
    lastMileStep2Desc: '업계 지식, 워크플로, 전문 기술',
    lastMileStep3: '당신의 대체자',
    lastMileStep3Desc: '당신의 구체적인 일을 하는 AI',
    lastMileArrow1: '파인튜닝 / 스킬',
    lastMileArrow2: '전문화',
    lastMileWarning: '당신의 경험 데이터가 개방적일수록 AI는 라스트 마일을 더 빨리 넘어 당신을 대체합니다.',
    platformTitle: '당신이 이미 동의한 것',
    platformSubtitle: '대부분의 사람들은 모르는 사이에 데이터를 AI 훈련에 사용하는 것에 "동의"했습니다. 세부 조항:',
    platformName: '플랫폼',
    platformClause: 'AI 훈련 조항',
    platformRisk: '위험',
    platformTrains: '무엇을 훈련하는가',
    platformRiskHigh: '명시적 훈련',
    platformRiskMedium: '모호함',
    platformRiskLow: '옵트아웃 가능',
    feedbackLoopTitle: '피드백 루프',
    feedbackLoopDesc: '당신이 데이터 생성 → 기업이 수집 → AI가 훈련 → AI가 당신을 대체 → 기업이 이익',
    feedbackLoopExample: '실제 사례: 개발자들이 GitHub에서 코드 작성 → Copilot이 훈련에 사용 → 기업들이 주니어 개발자 채용 감소',
    feedbackLoopStat: '훈련 데이터를 만든 사람이 가장 먼저 대체된다.',
    protectionTitle: '마지막 방어선을 지켜라',
    protectionSubtitle: '경험 데이터를 보호하기 위한 실행 가능한 단계:',
    protection1: '사용하는 모든 플랫폼에서 AI 훈련 옵트아웃 설정 확인',
    protection2: '고용주의 데이터 수집 및 AI 훈련 정책 이해',
    protection3: '디지털화할 수 없는 스킬 개발: 판단력, 인간관계, 물리적 기술',
    protection4: '독점 지식을 인덱싱되지 않는 비공개 형식으로 보관',
    protection5: '권리를 알기: GDPR(EU) 및 개인정보보호법이 당신에게 통제권을 부여',
    viewFullDetails: '데이터 보호 가이드 전체 보기',
    viewFullDetailsCta: '플랫폼이 수집하는 것, 피드백 루프, 보호 방법을 확인하세요.',
  },
  de: {
    backToHome: '← Zurück zur Startseite',
    dataThreatTitle: 'Ihre Daten trainieren KI, Sie zu ersetzen',
    dataThreatSubtitle: 'Fähigkeit ist die letzte Meile von allgemeiner KI zu Ihrem spezifischen Job. Ihre Erfahrungsdaten sind die letzte Verteidigungslinie.',
    lastMileTitle: 'Das Letzte-Meile-Problem',
    lastMileDesc: 'Ein Grundmodell allein kann Ihren Job nicht machen. Aber mit Ihren Branchendaten, Workflows und Expertise — wird es zu Ihrem Ersatz.',
    lastMileStep1: 'Grundmodell',
    lastMileStep1Desc: 'Allgemeine Fähigkeit, keine Spezialisierung',
    lastMileStep2: 'Ihre Daten & Erfahrung',
    lastMileStep2Desc: 'Branchenwissen, Workflows, Expertise',
    lastMileStep3: 'Ihr Ersatz',
    lastMileStep3Desc: 'KI, die IHREN spezifischen Job macht',
    lastMileArrow1: 'Feinabstimmung / Skills',
    lastMileArrow2: 'Spezialisierung',
    lastMileWarning: 'Je offener Ihre Erfahrungsdaten sind, desto schneller überbrückt KI die letzte Meile, um Sie zu ersetzen.',
    platformTitle: 'Dem haben Sie bereits zugestimmt',
    platformSubtitle: 'Die meisten Menschen haben unwissentlich „zugestimmt", dass ihre Daten KI trainieren. Das steht im Kleingedruckten:',
    platformName: 'Plattform',
    platformClause: 'KI-Trainingsklausel',
    platformRisk: 'Risiko',
    platformTrains: 'Was trainiert wird',
    platformRiskHigh: 'Explizites Training',
    platformRiskMedium: 'Mehrdeutig',
    platformRiskLow: 'Opt-out verfügbar',
    feedbackLoopTitle: 'Die Rückkopplungsschleife',
    feedbackLoopDesc: 'Sie erstellen Daten → Unternehmen sammelt → KI trainiert → KI ersetzt Sie → Unternehmen profitiert',
    feedbackLoopExample: 'Reales Beispiel: Entwickler schrieben Code auf GitHub → Copilot wurde damit trainiert → Unternehmen stellen jetzt weniger Junior-Entwickler ein',
    feedbackLoopStat: 'Die Menschen, die die Trainingsdaten erstellt haben, werden zuerst ersetzt.',
    protectionTitle: 'Schützen Sie Ihre letzte Verteidigungslinie',
    protectionSubtitle: 'Umsetzbare Schritte zum Schutz Ihrer Erfahrungsdaten:',
    protection1: 'Überprüfen Sie die KI-Training-Opt-out-Einstellungen auf jeder Plattform',
    protection2: 'Verstehen Sie die Datensammlungs- und KI-Trainingsrichtlinien Ihres Arbeitgebers',
    protection3: 'Entwickeln Sie nicht-digitalisierbare Fähigkeiten: Urteilsvermögen, Beziehungen, Handwerk',
    protection4: 'Bewahren Sie proprietäres Wissen in nicht-indizierten, privaten Formaten auf',
    protection5: 'Kennen Sie Ihre Rechte: DSGVO (EU) und Datenschutzgesetze geben Ihnen Kontrolle',
    viewFullDetails: 'Vollständigen Datenschutzleitfaden anzeigen',
    viewFullDetailsCta: 'Sehen Sie, was Plattformen sammeln, die Rückkopplungsschleife und wie Sie sich schützen können.',
  },
};
